CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cargo_scans (
  id SERIAL PRIMARY KEY,
  image_url TEXT NOT NULL,
  risk_score INT DEFAULT 0,
  risk_level VARCHAR(20) DEFAULT 'LOW',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS detections (
  id SERIAL PRIMARY KEY,
  scan_id INT REFERENCES cargo_scans(id) ON DELETE CASCADE,
  object_name VARCHAR(100) NOT NULL,
  confidence FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS alerts (
  id SERIAL PRIMARY KEY,
  scan_id INT REFERENCES cargo_scans(id) ON DELETE CASCADE,
  alert_type VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
